language: ruby
rvm:
  - 2.2
before_install:
  - gem install bundler

deploy:
  provider: heroku
  api_key: b52e2534-ef92-490d-b88e-2acb20809114
    secure: "CPFnHmGFkXEaWgBW1F7GTXWHsBnv93LxrmJT7rf+o0yA1QdN1vh+c02RZpzj0c2s/8NIrneNKst0BV9wDB7HPfpAOq+ab0oYKrdrbee/tKPz75j1keV4RayRwjaw1GA+Aq5uZpq6c7TGiPRrBLClu5ln5rD2T1Wlb04ZGovrn48KFoZ3ZgeroyQ+W4/LxfMjQ60eSVWMzCSaQWZikZ8HObuBC3H92MU3O7iPJwQs1+2ljcBp0Q2oAYENk1OEILOJ4bvNox1IDhw392b3pRPSEv+1TEv+ae3QZWL6UEeyMEeT15x6TFOsioqA0NQVO0NNIwYcqtTCk+97Fy8Y5ICZSyJQF3mTmcvOapwI9wdaZhKJCbRQMRgo2bsVWG6xepqMpai1LGbpv5fp3k70e7XwM3LSK4sqP8C890gHcydm7lFv7l0Y9LUUSgqyy2wD5+i6CqklHkxLLLRSHycNf4XgFrfnnTVEG5xSz0wLveLkI91GNw6od3fLPZ4Il1Djw6MEbCZVuIUJpgHiOx+Sb28zB28OaHcwcioJ/3GjDkDjsKU7WjO75mwqBkVZrKlBv91UPnirZ1jzsY29fQwjziyrw5an5Of5LHzFI3kUrTUXiJd9rb5Pr6/SzdLHf/9fDFrmnHxdZIPGZRbBQo/3nlfNCcURhPF/147VOW+aYoiT8C4="

  app: sheltered-beach-99276

