# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 048a0251f50fc173648ad028ee8e85cdbd7b8875d7710416762fd3cd48e8ceeff493468c0ba6c02b0198b6a71e615b8528cf1517522aa0c877098bed81cfefa7

test:
  secret_key_base: a7ab3ce8368e5fca9a88cb32525ea574f3e041c0b95c3db98088581d7132331ad7c28ac44f5883173382f251a5766658e1ad781b1efeea94b62157b0db18fd19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
